version: '3.9'

services:
    postgres_user:
        image: 'postgres:16.0'
        container_name: postgres_user_container
        env_file:
            - .env
        environment:
            - 'POSTGRES_DB=${DB_NAME_USER}'
            - 'POSTGRES_PASSWORD=${DB_USER}'
            - 'POSTGRES_USER=${DB_PASSWORD}'
        ports:
            - '5432:5432'

    postgres_event:
        image: 'postgres:16.0'
        container_name: postgres_event_container
        env_file:
            - .env
        environment:
            - 'POSTGRES_DB=${DB_NAME_EVENT}'
            - 'POSTGRES_PASSWORD=${DB_USER}'
            - 'POSTGRES_USER=${DB_PASSWORD}'
        ports:
            - '5433:5432'

    postgres_email:
        image: 'postgres:16.0'
        container_name: postgres_email_container
        env_file:
            - .env
        environment:
            - 'POSTGRES_DB=${DB_NAME_EMAIL}'
            - 'POSTGRES_PASSWORD=${DB_USER}'
            - 'POSTGRES_USER=${DB_PASSWORD}'
        ports:
            - '5434:5432'

    postgres_rate:
        image: 'postgres:16.0'
        container_name: postgres_rate_container
        env_file:
            - .env
        environment:
            - 'POSTGRES_DB=${DB_NAME_RATE}'
            - 'POSTGRES_PASSWORD=${DB_USER}'
            - 'POSTGRES_USER=${DB_PASSWORD}'
        ports:
            - '5435:5432'

    postgres_customer:
        image: 'postgres:16.0'
        container_name: postgres_customer_container
        env_file:
            - .env
        environment:
            - 'POSTGRES_DB=${DB_NAME_CUSTOMER}'
            - 'POSTGRES_PASSWORD=${DB_USER}'
            - 'POSTGRES_USER=${DB_PASSWORD}'
        ports:
            - '5436:5432'

    rabbitmq:
        image: 'rabbitmq:3-management'
        container_name: rabbitmq_container
        ports:
            - '5672:5672'
            - '15672:15672'

    prometheus:
        image: prom/prometheus
        container_name: prometheus_container
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml

    victoriametrics:
        image: victoriametrics/victoria-metrics
        container_name: victoriametrics_container
        ports:
            - "8428:8428"
        command:
            - "-promscrape.config=/etc/prometheus/prometheus.yml"
        volumes:
            - ./victoria.yml:/etc/prometheus/prometheus.yml

    grafana:
        image: grafana/grafana
        container_name: grafana_container
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - grafana-storage:/var/lib/grafana

volumes:
    grafana-storage: